---
- name: Update apt package index
  apt:
    update_cache: yes

- name: Install prerequisite packages
  apt:
    name:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    state: present

- name: Add Docker’s official GPG key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Set up Docker repository
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
    state: present

- name: Update apt package index again
  apt:
    update_cache: yes

- name: Install Docker Engine, CLI and containerd
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present

- name: Install Docker Compose plugin
  apt:
    name: docker-compose-plugin
    state: present

- name: Ensure Docker service is started and enabled
  service:
    name: docker
    state: started
    enabled: yes

- name: Add user '{{ ansible_user }}' to docker group
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes
